"""Dice RPG v7 expansion — +90 dice (210 -> 300) and themed banner data.

Every die here uses ONLY param keys the client engine already simulates
(omen/fracture/combo/chill/gravity/bleed/plague/energy/shield/lifesteal/
execute/aura/team buffs/break/summon/echo/time-mark/mirage/jackpot/etc.),
so all 90 are fully functional in battle with zero engine changes.
"""

_BASE = {
    "COMMON":    {"hp": 980,  "atk": 110, "def": 70,  "spd": 100},
    "RARE":      {"hp": 1090, "atk": 150, "def": 66,  "spd": 108},
    "LEGENDARY": {"hp": 1320, "atk": 162, "def": 104, "spd": 112},
    "MYTHIC":    {"hp": 1300, "atk": 158, "def": 82,  "spd": 105},
    "ETERNAL":   {"hp": 1780, "atk": 204, "def": 110, "spd": 110},
}


def _mk(spec):
    r = spec["r"]
    h = sum(ord(c) for c in spec["id"])
    st = dict(_BASE[r])
    st["hp"]  = int(st["hp"]  * (0.94 + (h % 13) / 100.0))
    st["atk"] = int(st["atk"] * (0.94 + ((h // 13) % 13) / 100.0))
    st["def"] = int(st["def"] * (0.94 + ((h // 169) % 13) / 100.0))
    st["spd"] = st["spd"] + (h % 9) - 4
    st.update(spec.get("st", {}))
    k = spec["kit"]
    d = {
        "id": spec["id"], "name": spec["nm"], "rarity": r,
        "element": spec["el"], "role": spec["ro"],
        "tags": spec.get("tg", []), "stats": st,
        "basic":   {"name": k[0], "desc": k[1]},
        "skill":   {"name": k[2], "desc": k[3]},
        "ult":     {"name": k[4], "desc": k[5]},
        "passive": {"name": k[6], "desc": k[7]},
        "lore": spec.get("lo", "A die forged for the v7 meta."),
        "voice": spec.get("vo", "\u201cRoll me.\u201d"),
        "params": spec.get("p", {}),
    }
    if spec.get("en"):
        d["engine"] = spec["en"]
    return d


_S = [
    # ─── ETERNAL (5) ────────────────────────────────────────────────────────
    dict(id="chronos_prime", nm="Chronos Prime", r="ETERNAL", el="Time", ro="Timeline Sovereign",
         tg=["Control"], en=["Control", "Energy"],
         kit=("Second Hand", "Strike and mark the target with a Time Mark.",
              "Rewind", "Advance the whole team's turns and grant 8 energy.",
              "Hour Zero", "Massive AoE; every Time Mark detonates and stuns.",
              "Inevitable", "Allies act 15% sooner; marks amplify all damage."),
         p={"time_mark": 1, "advance": 0.35, "ult_team_energy": 8, "spd_up": 0.15, "delay_pct": 0.3},
         lo="It does not tell time. Time tells it.", vo="\u201cYour turn never comes.\u201d"),
    dict(id="null_sovereign", nm="Null Sovereign", r="ETERNAL", el="Void", ro="Collapse Emperor",
         tg=["Fracture"], en=["Fracture", "Control"],
         kit=("Erasure", "Deal Void damage and apply 2 Fracture.",
              "Event Horizon", "Apply 3 Fracture to ALL enemies and seal buffs.",
              "Singularity", "AoE that triggers every Fracture threshold at once.",
              "Absence", "Enemy shields cannot form; Fracture ticks are amplified."),
         p={"basic_fracture": 2, "skill_fracture_all": 3, "ult_fracture_trigger": 1,
            "seal_turns": 2, "shield_break": 1, "ult_fracture_tick": 2},
         lo="Where its shadow lands, the ledger reads zero.", vo="\u201cSubtract everything.\u201d"),
    dict(id="dawnbreaker_apex", nm="Dawnbreaker Apex", r="ETERNAL", el="Light", ro="Radiant Vanguard",
         tg=["Sustain"], en=["Sustain", "Energy"],
         kit=("First Light", "Strike and shield the weakest ally.",
              "Zenith", "Cleanse the team, grant shields and 6 energy.",
              "Supernova", "Huge Light AoE; heals the team for damage dealt.",
              "Daybreak", "Team takes reduced damage and regenerates each round."),
         p={"basic_shield": 1, "skill_shield": 1, "cleanse_all": 1, "skill_energy": 6,
            "lifesteal": 0.4, "dr_pct": 0.15, "dr_turns": 99, "drift_heal": 0.04},
         lo="The last sunrise the Abyss ever saw.", vo="\u201cStand in my light.\u201d"),
    dict(id="worldroot_titan", nm="Worldroot Titan", r="ETERNAL", el="Earth", ro="Living Fortress",
         tg=["Break"], en=["Break", "Sustain"],
         st={"hp": 2350, "def": 160, "spd": 92},
         kit=("Landslide", "Heavy blow with bonus Break damage.",
              "Deep Roots", "Taunt, gain a massive shield and reflect damage.",
              "Continental Split", "Colossal AoE; +50% Break and exposes weakness.",
              "Bedrock", "An ATK/DEF aura anchors the whole team."),
         p={"break_gain": 1.5, "shield_pct": 0.4, "reflect": 0.3, "guard_turns": 2,
            "ult_break": 1.5, "break_vuln": 0.25, "break_vuln_turns": 2,
            "aura_atk": 0.12, "aura_def": 0.18},
         lo="Mountains are just its knuckles.", vo="\u201cI am the table.\u201d"),
    dict(id="crimson_paradox", nm="Crimson Paradox", r="ETERNAL", el="Blood", ro="Life-Debt Reaper",
         tg=["Sustain"], en=["Sustain", "Combo"],
         kit=("Tithe", "Strike and apply Bleed; heal for the damage.",
              "Blood Contract", "Spend 20% HP for a devastating twin strike.",
              "Red Equation", "AoE scaling with all Bleed; executes the dying.",
              "Paradox", "The lower its HP, the harder every face lands."),
         p={"basic_bleed": 2, "bleed_dmg": 0.06, "lifesteal": 0.5, "skill_hp_cost": 0.2,
            "twin_hit": 1, "ult_bleed_pct": 1.2, "execute_th": 0.3, "execute_pct": 0.8},
         lo="It pays its debts in other people's blood.", vo="\u201cEveryone bleeds even.\u201d"),

    # ─── MYTHIC (15) ────────────────────────────────────────────────────────
    dict(id="solar_tyrant", nm="Solar Tyrant", r="MYTHIC", el="Fire", ro="Ramp Carry",
         tg=["Combo"], en=["Combo"],
         kit=("Flare Lash", "Fire strike that stacks Combo.",
              "Coronal Whip", "Two blazing hits, each adding Combo.",
              "Helios Verdict", "Consume all Combo for a screen-wide inferno.",
              "Ascendant Heat", "ATK ramps every turn the sun still burns."),
         p={"basic_combo": 2, "skill_combo": 2, "skill_hits": 2, "combo_max": 12,
            "combo_burst": 1.4, "ramp_atk": 0.05},
         lo="A star that refused to set.", vo="\u201cKneel or burn.\u201d"),
    dict(id="glacier_empress", nm="Glacier Empress", r="MYTHIC", el="Ice", ro="Freeze Control",
         tg=["Control"], en=["Control"],
         kit=("Frost Edict", "Ice damage and 2 Chill.",
              "Winter Court", "Apply Chill to ALL enemies.",
              "Absolute Throne", "AoE that freezes everything past the threshold.",
              "Permafrost", "Chilled enemies deal less and act slower."),
         p={"basic_chill": 2, "skill_chill_all": 2, "ult_chill_all": 3, "freeze_at": 5, "delay_pct": 0.2},
         lo="Her palace is other people's stopped hearts.", vo="\u201cWinter is a verdict.\u201d"),
    dict(id="storm_herald", nm="Storm Herald", r="MYTHIC", el="Electric", ro="Energy Battery",
         tg=["Energy"], en=["Energy"],
         kit=("Static Sting", "Shock a foe and generate 3 energy.",
              "Conduction", "Give the team 6 energy and boost energy gain.",
              "Tempest Protocol", "AoE lightning; fully charges the fastest ally.",
              "Overcharge", "Round start: the team gains bonus energy."),
         p={"basic_energy": 3, "skill_give": 6, "energy_gain_buff": 0.3, "energy_buff_turns": 2,
            "ult_full_energy": 1, "round_energy": 2},
         lo="It announces storms it personally schedules.", vo="\u201cFeel the current.\u201d"),
    dict(id="gravemind_die", nm="Gravemind Die", r="MYTHIC", el="Dark", ro="Omen Detonator",
         tg=["Omen"], en=["Omen"],
         kit=("Whisper", "Dark strike applying 3 Omen.",
              "Chorus of Ends", "Apply 6 Omen to every enemy.",
              "Last Rites", "AoE; detonates all Omen twice, amplified.",
              "Buried Odds", "Your Omen detonations hit 30% harder."),
         p={"basic_omen": 3, "skill_omen_all": 6, "ult_omen_trig": 2, "omen_amp": 0.3},
         lo="Six feet under, six faces up.", vo="\u201cThe dead count cards.\u201d"),
    dict(id="verdant_curse", nm="Verdant Curse", r="MYTHIC", el="Nature", ro="Plague Gardener",
         tg=["Omen"], en=["Omen", "Sustain"],
         kit=("Spore Bite", "Nature damage and Plague spores.",
              "Blooming Rot", "Spread Plague to all enemies; heal per infected.",
              "Overgrowth", "AoE scaling with every Plague stack on the field.",
              "Mulch", "Enemies that die feed the team's health."),
         p={"basic_omen": 2, "skill_omen_all": 3, "ult_plague_pct": 1.0, "drift_heal": 0.05, "lifesteal": 0.25},
         lo="Its garden grows best on losing streaks.", vo="\u201cEverything composts.\u201d"),
    dict(id="zephyr_blade", nm="Zephyr Blade", r="MYTHIC", el="Wind", ro="Multi-Hit Assassin",
         tg=["Combo"], en=["Combo"],
         st={"spd": 128},
         kit=("Gale Cut", "A blindingly fast slash that stacks Combo.",
              "Thousand Winds", "Strike 4 times across random foes.",
              "Eye of the Storm", "Consume Combo for a shredding cyclone.",
              "Tailwind", "Grants the team speed; crits raise Combo."),
         p={"basic_combo": 2, "skill_hits": 4, "combo_max": 10, "combo_burst": 1.3,
            "spd_buff": 0.12, "crit_up": 0.1},
         lo="You hear the win before you see the blade.", vo="\u201cToo slow. Always.\u201d"),
    dict(id="starfall_gambit", nm="Starfall Gambit", r="MYTHIC", el="Arcane", ro="Fortune Carry",
         tg=["Fortune"], en=["Fortune"],
         kit=("Comet Toss", "Arcane hit with a chance to strike twice.",
              "Meteor Wager", "Big hit; rerolls itself on a lucky face.",
              "Star Shower", "AoE that crits far more often than it should.",
              "House Money", "The team's luck (crit & fortune) rises."),
         p={"twin_hit": 1, "reroll_chance": 0.35, "crit_up": 0.25, "team_fortune": 0.15},
         lo="It bet on itself and the sky paid out.", vo="\u201cCatch a falling W.\u201d"),
    dict(id="iron_colossus", nm="Iron Colossus", r="MYTHIC", el="Physical", ro="Break Juggernaut",
         tg=["Break"], en=["Break"],
         st={"hp": 1750, "def": 130},
         kit=("Piston Punch", "Heavy blow with strong Break damage.",
              "Demolition", "Smash with +Break and expose the target.",
              "Wrecking Orbit", "AoE; broken enemies take brutal bonus damage.",
              "Plating", "Starts shielded; hits harder into Broken foes."),
         p={"break_gain": 1.4, "skill_break": 1.4, "break_vuln": 0.3, "break_vuln_turns": 2,
            "shield_pct": 0.3, "broken_bonus": 0.4},
         lo="Built to break banks. Renovated to break bones.", vo="\u201cStructural failure: you.\u201d"),
    dict(id="plague_regent", nm="Plague Regent", r="MYTHIC", el="Poison", ro="DoT Overlord",
         tg=["Omen"], en=["Omen"],
         kit=("Venom Writ", "Poison hit applying Bleed and Omen.",
              "Royal Decree", "Bleed ALL enemies; their wounds fester.",
              "Pandemic Crown", "AoE scaling with all Bleed and Plague stacks.",
              "Court of Flies", "Damage-over-time effects tick 25% harder."),
         p={"basic_bleed": 2, "basic_omen": 1, "bleed_dmg": 0.07, "ult_bleed_pct": 1.0,
            "ult_plague_pct": 0.6, "omen_amp": 0.25},
         lo="Long live the king. Nothing else does.", vo="\u201cCoughs are applause.\u201d"),
    dict(id="lumen_saint", nm="Lumen Saint", r="MYTHIC", el="Light", ro="Immortal Support",
         tg=["Sustain"], en=["Sustain"],
         kit=("Blessing", "Light damage; shield the most wounded ally.",
              "Sanctuary", "Cleanse and shield the entire team.",
              "Miracle", "AoE heal-strike; grants brief immunity.",
              "Halo", "Allies below 30% HP take far less damage."),
         p={"basic_shield": 1, "skill_shield": 1, "cleanse_all": 1, "immunity_turns": 1,
            "lifesteal": 0.3, "dr_pct": 0.2, "dr_turns": 2},
         lo="Canonized by the only jury that matters: survivors.", vo="\u201cNot today. Not ever.\u201d"),
    dict(id="bloodpact_baron", nm="Bloodpact Baron", r="MYTHIC", el="Blood", ro="HP-Cost Nuker",
         tg=["Sustain"], en=["Sustain", "Combo"],
         kit=("Down Payment", "Strike and Bleed; heal for a cut of damage.",
              "Foreclosure", "Spend 15% HP to hit twice, brutally.",
              "Debt Called", "AoE executing enemies below the red line.",
              "Compound Interest", "Damage grows as its HP shrinks."),
         p={"basic_bleed": 2, "lifesteal": 0.35, "skill_hp_cost": 0.15, "twin_hit": 1,
            "execute_th": 0.25, "execute_pct": 0.6, "bleed_dmg": 0.05},
         lo="Signs every contract in someone else's ink.", vo="\u201cPay up. In full.\u201d"),
    dict(id="timeweaver", nm="Timeweaver", r="MYTHIC", el="Time", ro="Tempo Control",
         tg=["Control"], en=["Control", "Energy"],
         kit=("Stitch", "Strike and place a Time Mark.",
              "Unravel", "Delay all enemies on the timeline.",
              "Loom of Hours", "AoE; marked enemies are stunned and shredded.",
              "Thread Count", "Allies gain speed; marks slow their bearers."),
         p={"time_mark": 1, "delay_pct": 0.3, "spd_up": 0.1, "advance": 0.2},
         lo="Deadlines are its favorite weapon.", vo="\u201cYour schedule is mine.\u201d"),
    dict(id="void_gambler", nm="Void Gambler", r="MYTHIC", el="Void", ro="Jackpot Transformer",
         tg=["Fortune"], en=["Fortune"],
         kit=("Ante Up", "Void hit that feeds the jackpot meter.",
              "Double Down", "Big hit; a win doubles it into a Jackpot state.",
              "Cash Out", "AoE spending the Jackpot for absurd damage.",
              "Rigged Table", "Fortune effects roll in its favor."),
         p={"skill_jackpot": 1, "transform_cost": 45, "reroll_chance": 0.25, "team_fortune": 0.1},
         lo="It bet the void. The void folded.", vo="\u201cAll in. Again.\u201d"),
    dict(id="quake_warden", nm="Quake Warden", r="MYTHIC", el="Earth", ro="Gravity Tank",
         tg=["Control"], en=["Control", "Break"],
         st={"hp": 1700, "def": 125},
         kit=("Tremor", "Strike and apply Gravity.",
              "Fault Line", "Apply Gravity to ALL enemies.",
              "Deep Impact", "AoE; Weighed enemies are crushed for bonus ticks.",
              "Ballast", "Heavy enemies hit this warden for less."),
         p={"basic_gravity": 2, "skill_gravity_all": 2, "weighed_at": 5, "ult_gravity_tick": 2,
            "dr_pct": 0.15, "dr_turns": 99},
         lo="It holds grudges the way planets hold moons.", vo="\u201cDown. Stay down.\u201d"),
    dict(id="mirror_monarch", nm="Mirror Monarch", r="MYTHIC", el="Arcane", ro="Echo Amplifier",
         tg=["Combo"], en=["Combo", "Control"],
         kit=("Reflection", "Arcane hit; a mirage repeats a fraction of it.",
              "Hall of Mirrors", "Summon mirages that copy your next strikes.",
              "Coronation of Glass", "AoE; every echo this battle replays at once.",
              "Symmetry", "Stores damage dealt and returns it as echoes."),
         p={"basic_mirage": 1, "ult_mirages": 2, "echo_store": 0.3, "echo_repeat_pct": 0.5, "echo_dmg": 0.35},
         lo="Every reflection is a rematch.", vo="\u201cWhich one won?\u201d"),

    # ─── LEGENDARY (20) ────────────────────────────────────────────────────
    dict(id="ashen_duke", nm="Ashen Duke", r="LEGENDARY", el="Fire", ro="Burn Skirmisher", tg=["Combo"], en=["Combo"],
         kit=("Cinder Jab", "Fire hit stacking Combo.", "Ember Waltz", "Two hits, each stacking Combo.",
              "Ash Gala", "Consume Combo for a fiery burst.", "Slow Burn", "ATK creeps upward each turn."),
         p={"basic_combo": 1, "skill_combo": 1, "skill_hits": 2, "combo_max": 8, "ramp_atk": 0.04},
         lo="Nobility, but flammable.", vo="\u201cDance faster.\u201d"),
    dict(id="rimefang", nm="Rimefang", r="LEGENDARY", el="Ice", ro="Chill Striker", tg=["Control"], en=["Control"],
         kit=("Cold Bite", "Ice damage with 2 Chill.", "Shatter Fang", "Hit; bonus vs Chilled targets.",
              "Glacial Maw", "AoE Chill everything.", "Frostbite", "Chill it applies bites deeper."),
         p={"basic_chill": 2, "ult_chill_all": 2, "freeze_at": 6},
         lo="Teeth first, apologies never.", vo="\u201cBrrr-utal.\u201d"),
    dict(id="volt_matron", nm="Volt Matron", r="LEGENDARY", el="Electric", ro="Team Battery", tg=["Energy"], en=["Energy"],
         kit=("Spark", "Shock and gain 2 energy.", "Power Grid", "Give the team 5 energy.",
              "Blackout Ball", "AoE; refunds team energy.", "Live Wire", "Round start energy trickle."),
         p={"basic_energy": 2, "skill_give": 5, "ult_team_energy": 5, "round_energy": 1},
         lo="Runs the grid. And the group chat.", vo="\u201cStay charged, dears.\u201d"),
    dict(id="dread_notary", nm="Dread Notary", r="LEGENDARY", el="Dark", ro="Omen Stacker", tg=["Omen"], en=["Omen"],
         kit=("Stamp", "Dark hit applying 2 Omen.", "Seal of Ruin", "Apply 5 Omen to a foe.",
              "Filed in Black", "AoE; detonate all Omen once.", "Fine Print", "Omen detonations hit harder."),
         p={"basic_omen": 2, "skill_omen": 5, "ult_omen_trig": 1, "omen_amp": 0.2},
         lo="Signs death certificates in advance.", vo="\u201cInitial here. And here.\u201d"),
    dict(id="briar_witch", nm="Briar Witch", r="LEGENDARY", el="Nature", ro="Thorn Sustain", tg=["Sustain"], en=["Sustain"],
         kit=("Thorn Lash", "Nature hit; heal a little.", "Bramble Ward", "Shield the team with thorns that reflect.",
              "Rose Riot", "AoE; heal per enemy struck.", "Photosynthesis", "Regenerates the team slowly."),
         p={"lifesteal": 0.25, "skill_shield": 1, "reflect": 0.2, "drift_heal": 0.04},
         lo="Her garden bites back.", vo="\u201cEvery rose, darling.\u201d"),
    dict(id="squall_dancer", nm="Squall Dancer", r="LEGENDARY", el="Wind", ro="Speed Support", tg=["Energy"], en=["Energy"],
         st={"spd": 124},
         kit=("Step In", "Quick hit; gain energy.", "Slipstream", "Advance an ally's turn.",
              "Hurricane Waltz", "AoE; team acts sooner.", "Featherweight", "Grants team speed."),
         p={"basic_energy": 2, "advance": 0.3, "spd_buff": 0.1},
         lo="Footwork you can't follow.", vo="\u201cKeep up~\u201d"),
    dict(id="arc_lexicon", nm="Arc Lexicon", r="LEGENDARY", el="Arcane", ro="Echo Caster", tg=["Combo"], en=["Combo"],
         kit=("Cite", "Arcane bolt; stores an echo.", "Cross-Reference", "Hit twice from stored pages.",
              "Full Bibliography", "AoE; replays stored echoes.", "Appendix", "Stores a cut of damage dealt."),
         p={"echo_store": 0.25, "skill_hits": 2, "echo_repeat_pct": 0.4, "echo_dmg": 0.3},
         lo="Reads you your rights, then the eulogy.", vo="\u201cAs cited previously.\u201d"),
    dict(id="basalt_sentinel", nm="Basalt Sentinel", r="LEGENDARY", el="Earth", ro="Wall", tg=["Break"], en=["Break", "Sustain"],
         st={"hp": 1650, "def": 135, "spd": 96},
         kit=("Slab Slam", "Heavy Break blow.", "Bulwark", "Huge self shield; taunt.",
              "Monolith Drop", "AoE Break smash.", "Igneous", "Reflects a cut of damage taken."),
         p={"break_gain": 1.3, "shield_pct": 0.35, "guard_turns": 2, "ult_break": 1.3, "reflect": 0.25},
         lo="Older than the house. Harder, too.", vo="\u201c...\u201d"),
    dict(id="haemo_countess", nm="Haemo Countess", r="LEGENDARY", el="Blood", ro="Bleed DPS", tg=["Sustain"], en=["Sustain"],
         kit=("Red Sip", "Strike, Bleed, heal.", "Transfusion", "Big hit; heal the weakest ally.",
              "Crimson Ball", "AoE scaling with Bleed.", "Vintage", "Bleeds tick harder."),
         p={"basic_bleed": 2, "lifesteal": 0.3, "ult_bleed_pct": 0.8, "bleed_dmg": 0.06},
         lo="Prefers her vintages still warm.", vo="\u201cA toast \u2014 to you.\u201d"),
    dict(id="toxin_broker", nm="Toxin Broker", r="LEGENDARY", el="Poison", ro="Plague Dealer", tg=["Omen"], en=["Omen"],
         kit=("Sample", "Poison hit; apply Omen.", "Distribution", "Spread Omen to all enemies.",
              "Market Crash", "AoE scaling with Plague.", "Cut Product", "DoTs tick a little harder."),
         p={"basic_omen": 2, "skill_omen_all": 2, "ult_plague_pct": 0.7, "omen_amp": 0.15},
         lo="First dose is free. The rest cost HP.", vo="\u201cQuality product.\u201d"),
    dict(id="hourglass_judge", nm="Hourglass Judge", r="LEGENDARY", el="Time", ro="Delay Control", tg=["Control"], en=["Control"],
         kit=("Gavel", "Strike and place a Time Mark.", "Recess", "Delay an enemy heavily.",
              "Final Session", "AoE; marked foes get stunned.", "Court Order", "Enemies act later."),
         p={"time_mark": 1, "delay_pct": 0.35},
         lo="Justice delayed, weaponized.", vo="\u201cOverruled.\u201d"),
    dict(id="hollow_croupier", nm="Hollow Croupier", r="LEGENDARY", el="Void", ro="Debuff Support", tg=["Control"], en=["Control"],
         kit=("Rake In", "Void hit; steal energy.", "House Rules", "Seal enemy buffs.",
              "Table Wipe", "AoE; strip enemy buffs.", "Empty Sleeves", "Enemies generate less energy."),
         p={"steal_energy": 3, "seal_turns": 2, "strip_buff": 1},
         lo="Deals hands nobody can win.", vo="\u201cNo more bets.\u201d"),
    dict(id="sun_chorister", nm="Sun Chorister", r="LEGENDARY", el="Light", ro="Energy Healer", tg=["Sustain"], en=["Sustain", "Energy"],
         kit=("Hymn", "Light hit; give 2 energy.", "Choir Swell", "Heal-shield the team; 4 energy.",
              "Crescendo", "AoE; team heals for damage.", "Perfect Pitch", "Team regen each round."),
         p={"basic_energy": 2, "skill_shield": 1, "skill_give": 4, "lifesteal": 0.25, "drift_heal": 0.03},
         lo="Sings the odds into key.", vo="\u201cOne more verse!\u201d"),
    dict(id="magma_shogun", nm="Magma Shogun", r="LEGENDARY", el="Fire", ro="Break DPS", tg=["Break"], en=["Break"],
         kit=("Lava Draw", "Fire slash with Break.", "Eruption Stance", "Big Break hit; expose weakness.",
              "Caldera Cut", "AoE; bonus into Broken foes.", "Tempered", "Hits Broken enemies harder."),
         p={"break_gain": 1.3, "skill_break": 1.3, "break_vuln": 0.2, "break_vuln_turns": 2, "broken_bonus": 0.3},
         lo="Forged his own sword. And the volcano.", vo="\u201cDraw. Melt. Sheathe.\u201d"),
    dict(id="frost_quartermaster", nm="Frost Quartermaster", r="LEGENDARY", el="Ice", ro="Shield Support", tg=["Sustain"], en=["Sustain"],
         kit=("Ration", "Ice hit; shield self.", "Provisions", "Shield the whole team.",
              "Winter Stockpile", "AoE; team gains shields.", "Cold Storage", "Shields it grants are thicker."),
         p={"basic_shield": 1, "skill_shield": 1, "ult_shield": 1, "shield_pct": 0.25},
         lo="Never runs out. Ever.", vo="\u201cInventory: full.\u201d"),
    dict(id="pit_fighter", nm="Pit Fighter", r="LEGENDARY", el="Physical", ro="Counter Bruiser", tg=["Break"], en=["Break"],
         st={"hp": 1550},
         kit=("Haymaker", "Big Physical blow.", "Guard Up", "Shield and counter stance.",
              "Championship Round", "Massive single-target smash.", "Chin", "Counters when struck."),
         p={"break_gain": 1.2, "shield_pct": 0.25, "guard_turns": 1, "reflect": 0.3},
         lo="Undefeated in fights that count.", vo="\u201cRing the bell.\u201d"),
    dict(id="moth_oracle", nm="Moth Oracle", r="LEGENDARY", el="Dark", ro="Omen Support", tg=["Omen"], en=["Omen", "Energy"],
         kit=("Dust Touch", "Dark hit; 2 Omen and 2 energy.", "Prophecy", "Apply 4 Omen; give team energy.",
              "Lamplight End", "AoE; detonate Omen once.", "Drawn to Ruin", "Allied hits add extra Omen."),
         p={"basic_omen": 2, "basic_energy": 2, "skill_omen": 4, "skill_give": 3, "ult_omen_trig": 1},
         lo="It read your future by eating it.", vo="\u201cThe flame agrees.\u201d"),
    dict(id="gale_admiral", nm="Gale Admiral", r="LEGENDARY", el="Wind", ro="Team Buffer", tg=["Energy"], en=["Energy"],
         kit=("Cutlass Gust", "Wind slash.", "Full Sail", "Team damage and speed up.",
              "Broadside", "AoE wind cannonade.", "Trade Winds", "Team ATK aura."),
         p={"team_dmg": 0.12, "spd_buff": 0.08, "aura_atk": 0.1},
         lo="Commands the only navy without ships.", vo="\u201cFair winds, foul foes.\u201d"),
    dict(id="marble_regime", nm="Marble Regime", r="LEGENDARY", el="Earth", ro="Gravity Enforcer", tg=["Control"], en=["Control"],
         kit=("Decree", "Strike with Gravity.", "Martial Law", "Gravity on all enemies.",
              "Statue Garden", "AoE; Weighed foes crushed.", "Iron Fist", "Weighed enemies deal less."),
         p={"basic_gravity": 2, "skill_gravity_all": 1, "weighed_at": 5, "ult_gravity_tick": 1},
         lo="Its constitution is a single word: heavier.", vo="\u201cComply.\u201d"),
    dict(id="wyrm_banker", nm="Wyrm Banker", r="LEGENDARY", el="Void", ro="Execute Finisher", tg=["Fortune"], en=["Fortune"],
         kit=("Collection", "Void hit; twin chance.", "Liquidation", "Big hit; executes the weak.",
              "Hoard Call", "AoE; crit-boosted.", "Dragon's Ledger", "Fortune favors its claws."),
         p={"twin_hit": 1, "execute_th": 0.2, "execute_pct": 0.5, "crit_up": 0.15, "team_fortune": 0.08},
         lo="Sleeps on debts instead of gold.", vo="\u201cAccount closed.\u201d"),

    # ─── RARE (30) ─────────────────────────────────────────────────────────
    dict(id="matchstick", nm="Matchstick", r="RARE", el="Fire", ro="Combo Starter", tg=["Combo"],
         kit=("Strike", "Fire hit; +1 Combo.", "Flare Up", "Two quick hits.", "Bonfire", "AoE burst from Combo.", "Kindling", "Combo builds a bit faster."),
         p={"basic_combo": 1, "skill_hits": 2, "combo_max": 6}),
    dict(id="sleet_pixie", nm="Sleet Pixie", r="RARE", el="Ice", ro="Chill Support", tg=["Control"],
         kit=("Flick", "Ice hit; 1 Chill.", "Cold Snap", "Chill all enemies once.", "Hailstorm", "AoE with Chill.", "Numb", "Chill slows a touch more."),
         p={"basic_chill": 1, "skill_chill_all": 1, "ult_chill_all": 1}),
    dict(id="battery_imp", nm="Battery Imp", r="RARE", el="Electric", ro="Battery", tg=["Energy"],
         kit=("Zap", "Shock; +2 energy.", "Jumpstart", "Give an ally 4 energy.", "Surge", "AoE; team +3 energy.", "Trickle", "Small round energy."),
         p={"basic_energy": 2, "give_energy": 4, "ult_team_energy": 3, "round_energy": 1}),
    dict(id="black_cat", nm="Black Cat", r="RARE", el="Dark", ro="Omen Applier", tg=["Omen"],
         kit=("Scratch", "Dark hit; 2 Omen.", "Crossed Path", "4 Omen on a foe.", "Nine Ends", "AoE; 2 Omen each.", "Bad Luck", "Omen hits slightly harder."),
         p={"basic_omen": 2, "skill_omen": 4, "ult_bonus_omen": 2, "omen_amp": 0.1}),
    dict(id="sap_medic", nm="Sap Medic", r="RARE", el="Nature", ro="Healer", tg=["Sustain"],
         kit=("Poke", "Nature hit; small heal.", "Salve", "Shield an ally.", "Bloom", "AoE; heal team.", "Chlorophyll", "Tiny team regen."),
         p={"lifesteal": 0.2, "skill_shield": 1, "drift_heal": 0.03}),
    dict(id="paper_kite", nm="Paper Kite", r="RARE", el="Wind", ro="Speedster", tg=["Energy"], st={"spd": 122},
         kit=("Dart", "Fast wind hit.", "Updraft", "Advance own turn.", "Kite Storm", "Quick AoE.", "Lightframe", "Naturally swift."),
         p={"advance": 0.25, "spd_up": 0.05}),
    dict(id="rune_clerk", nm="Rune Clerk", r="RARE", el="Arcane", ro="Echo Novice", tg=["Combo"],
         kit=("File", "Arcane hit; store echo.", "Duplicate", "Repeat a stored fraction.", "Archive Burst", "AoE echo release.", "Carbon Copy", "Stores a bit of damage."),
         p={"echo_store": 0.2, "echo_repeat_pct": 0.3, "echo_dmg": 0.25}),
    dict(id="pebble_golem", nm="Pebble Golem", r="RARE", el="Earth", ro="Mini Tank", tg=["Break"], st={"hp": 1350, "def": 100, "spd": 95},
         kit=("Bonk", "Break-heavy blow.", "Huddle", "Self shield; taunt.", "Rockslide", "AoE Break.", "Sturdy", "A touch of damage reduction."),
         p={"break_gain": 1.2, "shield_pct": 0.25, "guard_turns": 1, "dr_pct": 0.1, "dr_turns": 99}),
    dict(id="leech_dandy", nm="Leech Dandy", r="RARE", el="Blood", ro="Drain DPS", tg=["Sustain"],
         kit=("Sip", "Strike; heal a bit.", "Deep Draw", "Bleed and drain.", "Red Carpet", "AoE with Bleed scaling.", "Refined Palate", "Lifesteal up."),
         p={"basic_bleed": 1, "lifesteal": 0.3, "ult_bleed_pct": 0.5}),
    dict(id="vial_tosser", nm="Vial Tosser", r="RARE", el="Poison", ro="DoT Thrower", tg=["Omen"],
         kit=("Lob", "Poison hit; 1 Omen.", "Cocktail", "Omen to all enemies.", "Spill", "AoE Plague scaling.", "Residue", "DoTs linger harder."),
         p={"basic_omen": 1, "skill_omen_all": 1, "ult_plague_pct": 0.4}),
    dict(id="tick_tocker", nm="Tick Tocker", r="RARE", el="Time", ro="Delay Bot", tg=["Control"],
         kit=("Tick", "Hit and mark time.", "Tock", "Delay a foe.", "Alarm", "AoE; marked foes shred.", "Wound Up", "Slight team speed."),
         p={"time_mark": 1, "delay_pct": 0.2, "spd_up": 0.05}),
    dict(id="pocket_void", nm="Pocket Void", r="RARE", el="Void", ro="Energy Thief", tg=["Control"],
         kit=("Nibble", "Void hit; steal 2 energy.", "Vacuum", "Steal buffs' momentum (seal).", "Little Abyss", "AoE void pop.", "Hungry", "Steals a bit more."),
         p={"steal_energy": 2, "seal_turns": 1}),
    dict(id="candle_page", nm="Candle Page", r="RARE", el="Light", ro="Shield Page", tg=["Sustain"],
         kit=("Wick Flick", "Light hit; tiny shield.", "Candlelight", "Shield the team a little.", "Wax Wall", "AoE; small team shield.", "Steady Flame", "Shields slightly thicker."),
         p={"basic_shield": 1, "skill_shield": 1, "ult_shield": 1}),
    dict(id="scrap_pugilist", nm="Scrap Pugilist", r="RARE", el="Physical", ro="Brawler", tg=["Break"],
         kit=("Jab", "Quick punch.", "One-Two", "Hit twice.", "Haymaker Row", "AoE swing.", "Scar Tissue", "Counters occasionally."),
         p={"skill_hits": 2, "break_gain": 1.1, "reflect": 0.15}),
    dict(id="ozone_hound", nm="Ozone Hound", r="RARE", el="Electric", ro="Crit Chaser", tg=["Fortune"],
         kit=("Bite", "Shock bite.", "Pounce", "Crit-boosted lunge.", "Thunder Howl", "AoE bark.", "Static Fur", "Crit chance up."),
         p={"crit_up": 0.15, "twin_hit": 1}),
    dict(id="ivy_duelist", nm="Ivy Duelist", r="RARE", el="Nature", ro="Riposte", tg=["Sustain"],
         kit=("Lunge", "Nature thrust.", "Parry", "Shield; counter stance.", "Garden Flurry", "AoE slashes.", "Thorned", "Reflects light damage."),
         p={"skill_shield": 1, "guard_turns": 1, "reflect": 0.2}),
    dict(id="grit_miner", nm="Grit Miner", r="RARE", el="Earth", ro="Break Digger", tg=["Break"],
         kit=("Pick Swing", "Break blow.", "Deep Vein", "Big Break hit.", "Cave In", "AoE Break.", "Prospector", "Bonus into Broken."),
         p={"break_gain": 1.25, "skill_break": 1.2, "broken_bonus": 0.2}),
    dict(id="moon_moth", nm="Moon Moth", r="RARE", el="Dark", ro="Omen Flutter", tg=["Omen"],
         kit=("Dust", "Dark hit; 1 Omen.", "Powder", "3 Omen on a foe.", "Eclipse Dance", "AoE; detonate once.", "Nocturne", "Slight Omen amp."),
         p={"basic_omen": 1, "skill_omen": 3, "ult_omen_trig": 1, "omen_amp": 0.08}),
    dict(id="gust_courier", nm="Gust Courier", r="RARE", el="Wind", ro="Turn Support", tg=["Energy"], st={"spd": 120},
         kit=("Deliver", "Wind hit; +1 energy.", "Express", "Advance an ally.", "Parcel Storm", "AoE toss.", "Punctual", "Small team speed."),
         p={"basic_energy": 1, "advance": 0.2, "spd_buff": 0.05}),
    dict(id="glass_arbiter", nm="Glass Arbiter", r="RARE", el="Arcane", ro="Fragile Nuker", tg=["Fortune"], st={"hp": 900, "atk": 175},
         kit=("Shard", "Sharp arcane hit.", "Verdict", "Heavy strike; recoil.", "Sentence", "AoE burst.", "Brittle Power", "Hits hard, breaks easy."),
         p={"recoil": 0.1, "crit_up": 0.1, "dmg_up": 0.1}),
    dict(id="ember_squire", nm="Ember Squire", r="RARE", el="Fire", ro="Support DPS", tg=["Combo"],
         kit=("Torch Tap", "Fire hit; +1 Combo.", "Fan Flames", "Team damage up briefly.", "Bonita Blaze", "AoE flame.", "Loyal Heat", "Small team damage aura."),
         p={"basic_combo": 1, "team_dmg": 0.08}),
    dict(id="brine_oracle", nm="Brine Oracle", r="RARE", el="Ice", ro="Slow Support", tg=["Control"],
         kit=("Splash", "Ice hit.", "Tide Read", "Chill all; delay one.", "Riptide", "AoE wave.", "Salt Ward", "Small damage reduction."),
         p={"skill_chill_all": 1, "delay_pct": 0.15, "dr_pct": 0.08, "dr_turns": 99}),
    dict(id="fuse_rat", nm="Fuse Rat", r="RARE", el="Electric", ro="Suicide Sparker", tg=["Energy"],
         kit=("Gnaw", "Shock bite; +2 energy.", "Short Circuit", "Big hit; recoil.", "Blown Fuse", "Huge AoE; heavy recoil.", "Chewed Wires", "Feeds on stray current."),
         p={"basic_energy": 2, "recoil": 0.15, "overload_pct": 0.2}),
    dict(id="silk_surgeon", nm="Silk Surgeon", r="RARE", el="Blood", ro="Sustain Support", tg=["Sustain"],
         kit=("Suture", "Strike; heal lowest ally slightly.", "Graft", "Shield and mend an ally.", "Triage", "AoE; team lifesteal.", "Steady Hands", "Heals crit sometimes."),
         p={"lifesteal": 0.25, "skill_shield": 1, "drift_heal": 0.02}),
    dict(id="mold_scholar", nm="Mold Scholar", r="RARE", el="Poison", ro="Plague Studier", tg=["Omen"],
         kit=("Culture", "Poison hit; 1 Omen.", "Peer Review", "Omen to all; tiny heal.", "Thesis", "AoE Plague scaling.", "Published", "Plague ticks harder."),
         p={"basic_omen": 1, "skill_omen_all": 1, "ult_plague_pct": 0.5, "lifesteal": 0.1}),
    dict(id="sundial_monk", nm="Sundial Monk", r="RARE", el="Time", ro="Tempo Monk", tg=["Control"],
         kit=("Shadow Step", "Hit and mark.", "Meditation", "Advance self; gain energy.", "Noon Strike", "AoE; marked take extra.", "Patience", "Starts with energy."),
         p={"time_mark": 1, "advance": 0.2, "skill_energy": 4, "passive_energy": 10}),
    dict(id="static_jester", nm="Static Jester", r="RARE", el="Void", ro="Chaos Fortune", tg=["Fortune"],
         kit=("Prank", "Void hit; reroll chance.", "Juggle", "Random twin hits.", "Punchline", "AoE; crit-happy.", "Heckler", "Small team fortune."),
         p={"reroll_chance": 0.2, "twin_hit": 1, "crit_up": 0.1, "team_fortune": 0.05}),
    dict(id="beacon_cadet", nm="Beacon Cadet", r="RARE", el="Light", ro="Energy Support", tg=["Energy"],
         kit=("Signal", "Light hit; +2 energy.", "Flare", "Give team 3 energy.", "Lighthouse", "AoE; small team shield.", "On Watch", "Round energy trickle."),
         p={"basic_energy": 2, "skill_give": 3, "ult_shield": 1, "round_energy": 1}),
    dict(id="anvil_clerk", nm="Anvil Clerk", r="RARE", el="Physical", ro="Break Clerk", tg=["Break"],
         kit=("Stamp Down", "Break hit.", "Audit", "Expose target's weakness.", "Ledger Slam", "AoE Break.", "By The Book", "Bonus vs Broken."),
         p={"break_gain": 1.15, "break_vuln": 0.15, "break_vuln_turns": 2, "broken_bonus": 0.15}),
    dict(id="drift_lantern", nm="Drift Lantern", r="RARE", el="Light", ro="Wisp Summoner", tg=["Summon"], en=["Summon"],
         kit=("Glow Tap", "Light hit.", "Wisp Call", "Summon a wisp helper.", "Festival", "AoE; wisps strike too.", "Warm Glow", "Summons heal slightly."),
         p={"summon_pct": 0.25, "summon_max": 2, "ult_summons": 1, "drift_heal": 0.02}),

    # ─── COMMON (20) ───────────────────────────────────────────────────────
    dict(id="tin_pip", nm="Tin Pip", r="COMMON", el="Physical", ro="Starter Striker", tg=["Universal"],
         kit=("Tap", "A plain, honest hit.", "Double Tap", "Hit twice, politely.", "Tin Tantrum", "Small AoE.", "Cheap Alloy", "Nothing special. Reliable."),
         p={"skill_hits": 2}),
    dict(id="wax_pip", nm="Wax Pip", r="COMMON", el="Fire", ro="Ember Support", tg=["Universal", "Combo"],
         kit=("Warm Tap", "Fire hit; +1 Combo.", "Melt", "Softens a foe (expose).", "Drip Burst", "Small fire AoE.", "Soft Glow", "Combo trickles in."),
         p={"basic_combo": 1, "break_vuln": 0.1, "break_vuln_turns": 1}),
    dict(id="snow_pip", nm="Snow Pip", r="COMMON", el="Ice", ro="Chill Helper", tg=["Universal", "Control"],
         kit=("Cold Poke", "Ice hit; 1 Chill.", "Snowball", "Bigger Chill hit.", "Flurry", "Small AoE Chill.", "Frosty", "Chill sticks a little."),
         p={"basic_chill": 1}),
    dict(id="spark_pip", nm="Spark Pip", r="COMMON", el="Electric", ro="Battery Pip", tg=["Universal", "Energy"],
         kit=("Zappy", "Shock; +2 energy.", "Share Charge", "Give ally 3 energy.", "Sparkler", "Small AoE.", "Static", "Starts with energy."),
         p={"basic_energy": 2, "give_energy": 3, "passive_energy": 8}),
    dict(id="shade_pip", nm="Shade Pip", r="COMMON", el="Dark", ro="Omen Pip", tg=["Universal", "Omen"],
         kit=("Spook", "Dark hit; 1 Omen.", "Lurk", "2 Omen on a foe.", "Boo", "Small AoE.", "Creepy", "Omen amp, barely."),
         p={"basic_omen": 1, "skill_omen": 2, "omen_amp": 0.05}),
    dict(id="seed_pip", nm="Seed Pip", r="COMMON", el="Nature", ro="Heal Pip", tg=["Universal", "Sustain"],
         kit=("Sprout", "Nature hit; tiny heal.", "Water", "Small ally shield.", "Bloomlet", "Small AoE.", "Growing", "Regenerates slowly."),
         p={"lifesteal": 0.15, "skill_shield": 1, "drift_heal": 0.02}),
    dict(id="breeze_pip", nm="Breeze Pip", r="COMMON", el="Wind", ro="Fast Pip", tg=["Universal"], st={"spd": 118},
         kit=("Whoosh", "Quick wind hit.", "Gust", "Advance own turn a bit.", "Puff", "Small AoE.", "Light", "Just fast."),
         p={"advance": 0.15}),
    dict(id="glyph_pip", nm="Glyph Pip", r="COMMON", el="Arcane", ro="Echo Pip", tg=["Universal", "Combo"],
         kit=("Scribble", "Arcane hit; stores echo.", "Trace", "Repeat a fraction.", "Doodle Storm", "Small AoE.", "Notes", "Stores a little damage."),
         p={"echo_store": 0.15, "echo_repeat_pct": 0.25, "echo_dmg": 0.2}),
    dict(id="clay_pip", nm="Clay Pip", r="COMMON", el="Earth", ro="Tanky Pip", tg=["Universal", "Break"], st={"hp": 1150, "def": 85, "spd": 94},
         kit=("Thud", "Break-ish blow.", "Harden", "Small self shield.", "Clod Toss", "Small AoE.", "Dense", "A bit tough."),
         p={"break_gain": 1.1, "shield_pct": 0.2}),
    dict(id="ruby_pip", nm="Ruby Pip", r="COMMON", el="Blood", ro="Drain Pip", tg=["Universal", "Sustain"],
         kit=("Nip", "Strike; heal a sliver.", "Sip", "Bleed lightly.", "Red Ring", "Small AoE.", "Thirsty", "Minor lifesteal."),
         p={"basic_bleed": 1, "lifesteal": 0.2}),
    dict(id="spore_pip", nm="Spore Pip", r="COMMON", el="Poison", ro="DoT Pip", tg=["Universal", "Omen"],
         kit=("Puff", "Poison hit; 1 Omen.", "Cloud", "Omen to two foes (all, lightly).", "Mist", "Small AoE.", "Musty", "DoTs linger."),
         p={"basic_omen": 1, "skill_omen_all": 1}),
    dict(id="gear_pip", nm="Gear Pip", r="COMMON", el="Time", ro="Tick Pip", tg=["Universal", "Control"],
         kit=("Tick", "Hit and mark time.", "Wind Up", "Gain energy.", "Chime", "Small AoE.", "Clockwork", "Punctual by design."),
         p={"time_mark": 1, "skill_energy": 3}),
    dict(id="dust_pip", nm="Dust Pip", r="COMMON", el="Void", ro="Nibbler", tg=["Universal"],
         kit=("Nibble", "Void hit; steal 1 energy.", "Hoover", "Steal 2 energy.", "Dust Devil", "Small AoE.", "Vacuous", "Mildly hungry."),
         p={"steal_energy": 1}),
    dict(id="glow_pip", nm="Glow Pip", r="COMMON", el="Light", ro="Shield Pip", tg=["Universal", "Sustain"],
         kit=("Shine", "Light hit; tiny shield.", "Beam", "Shield an ally.", "Glimmer", "Small AoE.", "Nightlight", "Comforting."),
         p={"basic_shield": 1, "skill_shield": 1}),
    dict(id="brick_pip", nm="Brick Pip", r="COMMON", el="Physical", ro="Wall Pip", tg=["Universal", "Break"], st={"hp": 1200, "def": 90, "spd": 92},
         kit=("Wall Punch", "Sturdy blow.", "Stack Up", "Self shield; taunt.", "Masonry", "Small AoE.", "Mortared", "Reduces chip damage."),
         p={"shield_pct": 0.25, "guard_turns": 1, "dr_pct": 0.08, "dr_turns": 99}),
    dict(id="fizz_pip", nm="Fizz Pip", r="COMMON", el="Electric", ro="Crit Pip", tg=["Universal", "Fortune"],
         kit=("Pop", "Shock with crit chance.", "Shake", "Crit-boosted hit.", "Spray", "Small AoE.", "Carbonated", "Bubbly crits."),
         p={"crit_up": 0.1}),
    dict(id="petal_pip", nm="Petal Pip", r="COMMON", el="Nature", ro="Buff Pip", tg=["Universal"],
         kit=("Petal Tap", "Nature hit.", "Fragrance", "Team damage up slightly.", "Petal Rain", "Small AoE.", "Pleasant", "Tiny team aura."),
         p={"team_dmg": 0.05, "aura_atk": 0.05}),
    dict(id="coal_pip", nm="Coal Pip", r="COMMON", el="Fire", ro="Ramp Pip", tg=["Universal", "Combo"],
         kit=("Smolder", "Fire hit.", "Stoke", "ATK up briefly.", "Coal Toss", "Small AoE.", "Slow Cook", "ATK ramps slightly."),
         p={"ramp_atk": 0.03}),
    dict(id="lens_pip", nm="Lens Pip", r="COMMON", el="Arcane", ro="Focus Pip", tg=["Universal", "Fortune"],
         kit=("Focus Beam", "Arcane hit.", "Magnify", "Expose a foe briefly.", "Refract", "Small AoE.", "Clarity", "Sees weak points."),
         p={"break_vuln": 0.1, "break_vuln_turns": 1, "crit_up": 0.05}),
    dict(id="knuckle_pip", nm="Knuckle Pip", r="COMMON", el="Physical", ro="Counter Pip", tg=["Universal", "Break"],
         kit=("Sock", "Punchy punch.", "Brace", "Counter stance.", "Flurry", "Small AoE.", "Scrappy", "Counters sometimes."),
         p={"guard_turns": 1, "reflect": 0.15}),
]

V7_DICE = [_mk(s) for s in _S]
